//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudEvento
    {
        public int SolicitudEventoId { get; set; }
        public string TipoEvento { get; set; }
        public System.DateTime FechaHoraEvento { get; set; }
        public bool Confirmado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Eliminado { get; set; }
        public int CoordinadorId { get; set; }
        public int SalaId { get; set; }
    
        public virtual Coordinador Coordinador { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
